# Generated by Django 4.2 on 2025-08-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('badge_id', models.CharField(help_text='뱃지 고유 ID', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='뱃지명', max_length=100)),
                ('image_url', models.URLField(help_text='뱃지 이미지 URL')),
                ('condition', models.JSONField(help_text="획득 조건(JSON 예: {'region':'서울','collector_count':5})")),
                ('description', models.TextField(help_text='뱃지 설명')),
            ],
            options={
                'db_table': 'badge',
                'ordering': ['badge_id'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('awarded_at', models.DateTimeField(help_text='뱃지 획득 시각')),
                ('badge', models.ForeignKey(help_text='획득한 뱃지', on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='collector.badge')),
                ('user', models.ForeignKey(help_text='뱃지를 획득한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.user')),
            ],
            options={
                'db_table': 'user_badge',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('verified_by', models.CharField(choices=[('GPS', 'GPS'), ('Photo', 'Photo')], help_text='인증 방식(GPS or Photo)', max_length=10)),
                ('verified_lat', models.FloatField(help_text='인증 위도')),
                ('verified_lng', models.FloatField(help_text='인증 경도')),
                ('image_url', models.URLField(blank=True, help_text='사진 인증 URL (Photo 방식일 때)')),
                ('verified_at', models.DateTimeField(help_text='인증 시각')),
                ('content', models.ForeignKey(help_text='인증된 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='contents.content')),
                ('user', models.ForeignKey(help_text='인증한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='users.user')),
            ],
            options={
                'db_table': 'collector',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['awarded_at'], name='user_badge_awarded_fe61e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['verified_at'], name='collector_verifie_66c36b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collector',
            unique_together={('user', 'content')},
        ),
    ]
