# Generated by Django 4.2 on 2025-08-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('collector', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(help_text='뱃지를 획득한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.user'),
        ),
        migrations.AddField(
            model_name='collector',
            name='content',
            field=models.ForeignKey(help_text='인증된 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='contents.content'),
        ),
        migrations.AddField(
            model_name='collector',
            name='user',
            field=models.ForeignKey(help_text='인증한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['awarded_at'], name='user_badge_awarded_fe61e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['verified_at'], name='collector_verifie_66c36b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collector',
            unique_together={('user', 'content')},
        ),
    ]
