# Generated by Django 4.2 on 2025-08-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content_id', models.IntegerField(help_text='TourAPI 콘텐츠 ID', primary_key=True, serialize=False)),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('addr1', models.CharField(help_text='주소', max_length=255)),
                ('addr2', models.CharField(blank=True, help_text='상세주소', max_length=100)),
                ('cat1', models.CharField(help_text='대분류', max_length=10)),
                ('cat2', models.CharField(help_text='중분류', max_length=10)),
                ('cat3', models.CharField(help_text='소분류', max_length=10)),
                ('areacode', models.CharField(help_text='지역 코드', max_length=10)),
                ('sigungu_code', models.CharField(help_text='시군구코드', max_length=10)),
                ('map_x', models.FloatField(help_text='GPS X좌표')),
                ('map_y', models.FloatField(help_text='GPS Y좌표')),
                ('title', models.CharField(help_text='제목', max_length=255)),
                ('dong_region_code', models.CharField(help_text='법정동(시도) 코드', max_length=10)),
                ('dong_sigungu_code', models.CharField(help_text='법정동(시군구) 코드', max_length=10)),
                ('image2', models.URLField(blank=True, help_text='썸네일 이미지 URL', max_length=255)),
            ],
            options={
                'db_table': 'content',
                'ordering': ['content_id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('distance', models.CharField(blank=True, help_text='코스 총 거리', max_length=100)),
                ('take_time', models.CharField(blank=True, help_text='총 소요 시간', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_fee', models.CharField(blank=True, help_text='이용 요금', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
            ],
            options={
                'db_table': 'culture',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('event_place', models.CharField(blank=True, help_text='행사 장소', max_length=255, null=True)),
                ('event_startdate', models.DateField(blank=True, help_text='행사 시작일', null=True)),
                ('event_enddate', models.DateField(blank=True, help_text='행사 종료일', null=True)),
                ('play_time', models.CharField(blank=True, help_text='공연 시간', max_length=100)),
                ('use_fee', models.CharField(blank=True, help_text='이용 요금', max_length=100)),
            ],
            options={
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='FoodStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('first_menu', models.TextField(blank=True, help_text='대표 메뉴')),
                ('treat_menu', models.TextField(blank=True, help_text='취급 메뉴')),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('open_time', models.CharField(blank=True, help_text='영업일', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
            ],
            options={
                'db_table': 'food_store',
            },
        ),
        migrations.CreateModel(
            name='Leports',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
            ],
            options={
                'db_table': 'leports',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('fair_day', models.CharField(blank=True, help_text='장 서는 날', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('open_time', models.CharField(blank=True, help_text='영업 시간', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('sale_item', models.CharField(blank=True, help_text='판매 품목', max_length=255)),
            ],
            options={
                'db_table': 'shopping',
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
            ],
            options={
                'db_table': 'tourist_attraction',
            },
        ),
    ]
