# Generated by Django 4.2 on 2025-08-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content_id', models.IntegerField(help_text='TourAPI 콘텐츠 ID', primary_key=True, serialize=False)),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('addr1', models.CharField(help_text='주소', max_length=255)),
                ('addr2', models.CharField(blank=True, help_text='상세주소', max_length=255)),
                ('map_x', models.FloatField(help_text='GPS X좌표')),
                ('map_y', models.FloatField(help_text='GPS Y좌표')),
                ('tel', models.CharField(blank=True, help_text='연락처', max_length=50)),
                ('title', models.CharField(help_text='제목', max_length=255)),
                ('dong_region_code', models.IntegerField(help_text='법정동(시도) 코드')),
                ('dong_sigungu_code', models.IntegerField(help_text='법정동(시군구) 코드')),
            ],
            options={
                'db_table': 'content',
                'ordering': ['content_id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('distance', models.CharField(blank=True, help_text='코스 총 거리', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('take_time', models.CharField(blank=True, help_text='총 소요 시간', max_length=100)),
                ('theme', models.CharField(blank=True, help_text='코스 테마', max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('discount_info', models.TextField(blank=True, help_text='할인 정보')),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_fee', models.CharField(blank=True, help_text='이용 요금', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
            ],
            options={
                'db_table': 'culture',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('booking_place', models.CharField(blank=True, help_text='예매처', max_length=255)),
                ('discount_info', models.TextField(blank=True, help_text='할인 정보')),
                ('event_homepage', models.URLField(blank=True, help_text='행사 홈페이지')),
                ('event_startdate', models.DateField(blank=True, help_text='행사 시작일', null=True)),
                ('event_enddate', models.DateField(blank=True, help_text='행사 종료일', null=True)),
                ('place_info', models.TextField(blank=True, help_text='행사장 위치 안내')),
                ('play_time', models.CharField(blank=True, help_text='공연 시간', max_length=100)),
                ('program', models.TextField(blank=True, help_text='행사 프로그램')),
                ('use_time', models.CharField(blank=True, help_text='이용 요금', max_length=100)),
            ],
            options={
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('discount_info', models.TextField(blank=True, help_text='할인 정보')),
                ('open_time', models.CharField(blank=True, help_text='영업일', max_length=100)),
                ('packing', models.BooleanField(default=False, help_text='포장 가능 여부')),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('reservation', models.CharField(blank=True, help_text='예약 안내', max_length=255)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('scale', models.CharField(blank=True, help_text='규모', max_length=100)),
                ('treat_menu', models.TextField(blank=True, help_text='취급 메뉴')),
            ],
            options={
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='Leports',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('accom_count', models.IntegerField(blank=True, help_text='수용 인원', null=True)),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('exp_age_range', models.CharField(blank=True, help_text='체험 가능 연령', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('open_period', models.CharField(blank=True, help_text='운영 기간', max_length=100)),
                ('parking_fee', models.CharField(blank=True, help_text='주차 요금', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('reservation', models.CharField(blank=True, help_text='예약 안내', max_length=255)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_fee', models.CharField(blank=True, help_text='입장료', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
            ],
            options={
                'db_table': 'leports',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('fair_day', models.CharField(blank=True, help_text='장 서는 날', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('open_date', models.DateField(blank=True, help_text='개장일', null=True)),
                ('open_time', models.CharField(blank=True, help_text='영업 시간', max_length=100)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('sale_item', models.CharField(blank=True, help_text='판매 품목', max_length=255)),
                ('sale_item_cost', models.CharField(blank=True, help_text='판매 품목별 가격', max_length=255)),
                ('shop_guide', models.TextField(blank=True, help_text='매장 안내')),
            ],
            options={
                'db_table': 'shopping',
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각')),
                ('content', models.OneToOneField(help_text='연결된 콘텐츠(ID)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contents.content')),
                ('content_type_id', models.IntegerField(help_text='TourAPI 관광타입 ID')),
                ('chk_credit', models.CharField(blank=True, help_text='신용카드 가능정보', max_length=100)),
                ('info_center', models.CharField(blank=True, help_text='문의 및 안내', max_length=100)),
                ('open_date', models.DateField(blank=True, help_text='개장일', null=True)),
                ('parking', models.CharField(blank=True, help_text='주차 시설', max_length=100)),
                ('rest_date', models.CharField(blank=True, help_text='쉬는 날', max_length=100)),
                ('use_time', models.CharField(blank=True, help_text='이용 시간', max_length=100)),
            ],
            options={
                'db_table': 'tourist_attraction',
            },
        ),
    ]
