# Generated by Django 4.2 on 2025-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='map_x',
            field=models.FloatField(blank=True, help_text='GPS X좌표', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='map_y',
            field=models.FloatField(blank=True, help_text='GPS Y좌표', null=True),
        ),
    ]
