# Generated by Django 4.2 on 2025-08-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='FoodStore',
        ),
        migrations.AlterModelTable(
            name='foodstore',
            table='food_store',
        ),
    ]
