# Generated by Django 4.2 on 2025-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_content_map_x_alter_content_map_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='use_fee',
            field=models.TextField(blank=True, help_text='이용 요금'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='use_fee',
            field=models.TextField(blank=True, help_text='이용 요금'),
        ),
    ]
